version: "{build}"
skip_tags: true
install:
- cinst haxe
#- cinst php
before_build:
- haxe -version
- python --version
- set /P python3=<where python
- echo %python3%
- ln -sf python3 %python3%
- python3 --version
#- php -v
build_script:
- haxe build.hxml
