version: "{build}"
skip_tags: true
install:
- choco list --local-only
- cinst haxe -y
- cinst python-x86_32 -y
#- cinst php
before_build:
- haxe -version
- python --version
#- php -v
build_script:
- haxe build.hxml
